name: wbx
description: "Weight and balance calculator."
publish_to: 'none' 
version: 1.0.0

environment:
  sdk: ^3.9.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
